### ISSUE TITLE
Clone doesn't work properly after scaling world view

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#202] opened 2017-05-18 21:22 UTC

**Comment by amirebrahimi** [comment] 2017-06-02 17:54
I could not reproduce this. Can you share more repro steps?
![clonebug](https://cloud.githubusercontent.com/assets/904110/26738126/c761eeea-4781-11e7-9e6c-6e7a2ddbecaa.gif)

**Comment by amirebrahimi** [comment] 2017-06-02 23:45
Fixed in staging now

**Closed** 2017-06-02 23:45 UTC
Labels: regression
